[package]
name = "sillirc-mini"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
sillirc-lib = { path = "../sillirc-lib" }
colored = "3.0.0"

[lints]
workspace = true
