[package]
name = "sillirc-mini"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
serde_json = "1.0.145"

sillirc-lib = { path = "../sillirc-lib" }

[lints]
workspace = true
